# Generated by Django 3.1.7 on 2021-04-09 11:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0002_auto_20210408_1124'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('landlords', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_name', models.CharField(blank=True, max_length=250)),
                ('q1', models.CharField(blank=True, max_length=250)),
                ('q2', models.CharField(blank=True, max_length=250)),
                ('q3', models.CharField(blank=True, max_length=250)),
                ('q4', models.CharField(blank=True, max_length=250)),
                ('q5', models.CharField(blank=True, max_length=250)),
                ('q6', models.CharField(blank=True, max_length=250)),
                ('q7', models.CharField(blank=True, max_length=250)),
                ('q8', models.CharField(blank=True, max_length=250)),
                ('q9', models.CharField(blank=True, max_length=250)),
                ('status', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('date_updated', models.DateTimeField(auto_now=True, null=True)),
                ('added_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('company', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.usercompany')),
                ('landlord', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='landlords.landlord')),
            ],
        ),
        migrations.CreateModel(
            name='UnitNote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_note', models.TextField(blank=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('date_updated', models.DateTimeField(auto_now=True, null=True)),
                ('unit', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='units.unit')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
