# Generated by Django 3.1.7 on 2021-04-09 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('units', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='unit',
            name='status',
        ),
    ]
