# Generated by Django 3.1.7 on 2021-04-08 11:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0002_auto_20210408_1124'),
    ]

    operations = [
        migrations.CreateModel(
            name='Landlord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('email', models.CharField(blank=True, max_length=250)),
                ('phone', models.CharField(blank=True, max_length=250)),
                ('local_address', models.CharField(blank=True, max_length=250)),
                ('local_city', models.CharField(blank=True, max_length=250)),
                ('local_country', models.CharField(blank=True, max_length=250)),
                ('native_address', models.CharField(blank=True, max_length=250)),
                ('native_city', models.CharField(blank=True, max_length=250)),
                ('native_country', models.CharField(blank=True, max_length=250)),
                ('bank_name', models.CharField(blank=True, max_length=250)),
                ('branch_name', models.CharField(blank=True, max_length=250)),
                ('bank_account_details', models.CharField(blank=True, max_length=250)),
                ('ifsc_code', models.CharField(blank=True, max_length=250)),
                ('status', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('date_updated', models.DateTimeField(auto_now=True, null=True)),
                ('added_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('managed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.usercompany')),
            ],
        ),
        migrations.CreateModel(
            name='LandlordNote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('landlord_note', models.TextField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('date_updated', models.DateTimeField(auto_now=True, null=True)),
                ('landlord', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='landlords.landlord')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LandlordDocument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_name', models.CharField(blank=True, max_length=250)),
                ('doc_file', models.FileField(blank=True, null=True, upload_to='landlord_doc/')),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('date_updated', models.DateTimeField(auto_now_add=True, null=True)),
                ('added_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('landlord', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='landlords.landlord')),
            ],
        ),
    ]
