# Generated by Django 3.1.7 on 2021-04-15 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='task_title',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='taskmanager',
            name='is_lead_manager',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='task',
            name='task_details',
            field=models.TextField(null=True),
        ),
    ]
