# Generated by Django 3.1.7 on 2021-04-09 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_booking_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='booking_source',
            field=models.CharField(blank=True, choices=[('Source1', 'Source1'), ('Source2', 'Source2'), ('Source3', 'Source3')], max_length=250),
        ),
        migrations.AlterField(
            model_name='booking',
            name='booking_status',
            field=models.CharField(blank=True, choices=[('Status1', 'Status1'), ('Status2', 'Status2'), ('Status3', 'Status3')], max_length=250),
        ),
        migrations.AlterField(
            model_name='guest',
            name='gender',
            field=models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=250),
        ),
    ]
