# Generated by Django 3.1.7 on 2021-04-10 10:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bookings', '0003_auto_20210409_2101'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='email',
            new_name='no_of_guest',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='main_guest_name',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='phone',
        ),
        migrations.AlterField(
            model_name='booking',
            name='booking_status',
            field=models.CharField(blank=True, choices=[('Lead', 'Lead'), ('Confirmed', 'Confirmed'), ('Welcome Mail Sent', 'Welcome Mail Sent'), ('Document completed', 'Document completed'), ('Security Email', 'Security Email'), ('Checked In', 'Checked In'), ('Checkedout', 'Checkedout'), ('Cancelled', 'Cancelled')], default='Lead', max_length=250),
        ),
        migrations.CreateModel(
            name='MainGuestBookingMapping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('date_updated', models.DateTimeField(auto_now=True, null=True)),
                ('booking', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bookings.booking')),
                ('guest', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='bookings.guest')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
