# Generated by Django 3.1.7 on 2021-04-10 10:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20210408_1124'),
        ('bookings', '0004_auto_20210410_1004'),
    ]

    operations = [
        migrations.RenameField(
            model_name='guest',
            old_name='updated_by',
            new_name='added_by',
        ),
        migrations.RenameField(
            model_name='mainguestbookingmapping',
            old_name='updated_by',
            new_name='added_by',
        ),
        migrations.RenameField(
            model_name='mainguestbookingmapping',
            old_name='guest',
            new_name='main_guest',
        ),
        migrations.AddField(
            model_name='mainguestbookingmapping',
            name='company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.usercompany'),
        ),
        migrations.AlterField(
            model_name='mainguestbookingmapping',
            name='booking',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='bookings.booking'),
        ),
    ]
