# Generated by Django 3.1.7 on 2021-04-12 11:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0006_auto_20210410_1216'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReOrderStringLogic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lead', models.TextField(blank=True)),
                ('confirmed', models.TextField(blank=True)),
                ('welcome_mail_sent', models.TextField(blank=True)),
                ('document_completed', models.TextField(blank=True)),
                ('security_email', models.TextField(blank=True)),
                ('checked_in', models.TextField(blank=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('date_updated', models.DateTimeField(auto_now=True, null=True)),
                ('booking', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='bookings.booking')),
            ],
        ),
    ]
