# Generated by Django 3.1.7 on 2021-04-12 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0008_auto_20210412_1404'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='booking_status',
            field=models.CharField(blank=True, choices=[('stage_1', 'Lead'), ('stage_2', 'Confirmed'), ('stage_3', 'Welcome Mail Sent'), ('stage_4', 'Document completed'), ('stage_5', 'Security Email'), ('stage_6', 'Checked In'), ('stage_7', 'Checkedout'), ('stage_0', 'Cancelled')], default='Lead', max_length=250),
        ),
    ]
