# Generated by Django 3.1.7 on 2021-04-12 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0009_auto_20210412_1513'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reorderstringlogic',
            old_name='checked_in',
            new_name='satege_1',
        ),
        migrations.RenameField(
            model_name='reorderstringlogic',
            old_name='confirmed',
            new_name='satege_2',
        ),
        migrations.RenameField(
            model_name='reorderstringlogic',
            old_name='document_completed',
            new_name='satege_3',
        ),
        migrations.RenameField(
            model_name='reorderstringlogic',
            old_name='lead',
            new_name='satege_4',
        ),
        migrations.RenameField(
            model_name='reorderstringlogic',
            old_name='security_email',
            new_name='satege_5',
        ),
        migrations.RenameField(
            model_name='reorderstringlogic',
            old_name='welcome_mail_sent',
            new_name='satege_6',
        ),
    ]
