# Generated by Django 3.1.7 on 2021-04-12 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0010_auto_20210412_1516'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reorderstringlogic',
            old_name='satege_1',
            new_name='stage_1',
        ),
        migrations.RenameField(
            model_name='reorderstringlogic',
            old_name='satege_2',
            new_name='stage_2',
        ),
        migrations.RenameField(
            model_name='reorderstringlogic',
            old_name='satege_3',
            new_name='stage_3',
        ),
        migrations.RenameField(
            model_name='reorderstringlogic',
            old_name='satege_4',
            new_name='stage_4',
        ),
        migrations.RenameField(
            model_name='reorderstringlogic',
            old_name='satege_5',
            new_name='stage_5',
        ),
        migrations.RenameField(
            model_name='reorderstringlogic',
            old_name='satege_6',
            new_name='stage_6',
        ),
    ]
