# Generated by Django 3.1.7 on 2021-04-13 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0013_auto_20210412_2145'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='is_canceled',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='is_completed',
        ),
        migrations.AddField(
            model_name='mainguestbookingmapping',
            name='is_canceled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='mainguestbookingmapping',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='booking',
            name='booking_status',
            field=models.CharField(blank=True, choices=[('stage_1', 'Lead'), ('stage_2', 'Confirmed'), ('stage_3', 'Welcome Mail Sent'), ('stage_4', 'Document completed'), ('stage_5', 'Security Email'), ('stage_6', 'Checked In'), ('stage_7', 'Checkedout')], default='Lead', max_length=250),
        ),
    ]
